# (PART) Todo empieza con R {-}

# Instalando R y RStudio

## R y RStudio

* Instala [R, a free software environment for statistical computing and graphics][r-proj] desde el [CRAN][cran] de acuerdo a tu sistema operativo.

* Instala el entorno de desarrollo integrado [RStudio][rstudio-official]

Si previamente habías instalado alguna versión de R y RStudio en tu computadora, sugerimos reinstalar ambos para tener las versiones más actualizadas.

## RStudio Cloud

Aunque a lo largo del libro se mostrará a detalle el código de R usado, también proveeremos de links a proyectos de RStudio Cloud para facilitar reproducir los resultados aquí mostrados. Para acceder a tales proectos será necesario contar con una cuenta en [RStudio Cloud][rstudio-cloud].

## Recursos adicionales

Si no estás del todo familiarizado con el lenguaje, te recomendamos lo siguientes recursos donde podrás encontrar información útil sobre R y RStudio.

* [Cómo usar RStudio][rstudio-support]
* [RStudio para el aprendizaje de R][rstudio-R-help]
* [R: Preguntas Frecuentes][cran-faq]
* [R: Instalación y administración][cran-R-admin]

```{r links, child="links.md"}
```